language: ruby
cache: bundler
bundler_args: --without production

rvm:
        - 2.6.6
            
before_install:
         - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
         - source ~/.nvm/nvm.sh
         - nvm install 12.2 # for Node v5
         - node --version
         - gem install bundler:2.2.11
         - gem install rails

script: 
         - rails webpacker:install
         - RAILS_ENV=test bundle exec rails webpacker:compile
         - bundle exec rspec
