language: ruby
cache: bundler
bundler_args: --without production

rvm:
        - 2.6.6
            
before_install:
         - gem install bundler:2.2.11

script:
         - sudo npm cache clean -f
         - sudo npm install -g n
         - sudo n stable
         - RAILS_ENV=test bundle exec rails webpacker:compile
         - bundle exec rspec
