language: ruby
cache: bundler
bundler_args: --without production

rvm:
        - 2.6.6
            
before_install:
         - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
         - sudo apt-get install -y nodejs
         - node -v
         - gem install bundler:2.2.11

script:
         - bash 
         - RAILS_ENV=test bundle exec rails webpacker:compile
         - bundle exec rspec
