language: ruby
cache: bundler
bundler_args: --without production

rvm:
        - 2.6.6
            
before_install:
         - gem install bundler:2.2.11
         - RAILS_ENV=test bundle exec rails webpacker:compile

script:
         - bundle exec rspec
