language: ruby
cache: bundler
bundler_args: --without production

rvm:
        - 2.6.6
            
before_install:
         - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
         - source ~/.nvm/nvm.sh
         - nvm install 12.2 # for Node v5
         - node --version
         - gem install bundler:2.2.11

script: 
         - bundle exec rspec

deploy:
        provider: heroku
        api_key: 3320f90d-9c6a-453f-8757-fe2ef9e40558
        app: guarded-basin-59326
        run: "rake db:migrate"
        on:
                all_branches: true 
